com:
	npx hardhat compile

t:
	npx hardhat test

flow:
	npx hardhat run --network flow scripts/CardVerifierRouter.ts

bitkub:
	npx hardhat run --network bitkub scripts/CardVerifierRouter.ts

scroll:
	npx hardhat run --network scroll scripts/CardVerifierRouter.ts

se:
	npx hardhat run --network sepolia scripts/CardVerifierRouter.ts